/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  ScreenshotBuild,
} from '@stencil/core/screenshot';
import {
  ScreenshotDiff,
} from './helpers/screenshot-diff';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface LocalCompare {
    'buildA': ScreenshotBuild;
    'buildB': ScreenshotBuild;
    'imagesUrl': string;
    'jsonpUrl': string;
  }
  interface LocalCompareAttributes extends StencilHTMLAttributes {
    'buildA'?: ScreenshotBuild;
    'buildB'?: ScreenshotBuild;
    'imagesUrl'?: string;
    'jsonpUrl'?: string;
  }

  interface LocalPixelmatch {
    'diff': ScreenshotDiff;
  }
  interface LocalPixelmatchAttributes extends StencilHTMLAttributes {
    'diff'?: ScreenshotDiff;
  }

  interface ScreenshotLookup {}
  interface ScreenshotLookupAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'LocalCompare': Components.LocalCompare;
    'LocalPixelmatch': Components.LocalPixelmatch;
    'ScreenshotLookup': Components.ScreenshotLookup;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'local-compare': Components.LocalCompareAttributes;
    'local-pixelmatch': Components.LocalPixelmatchAttributes;
    'screenshot-lookup': Components.ScreenshotLookupAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLLocalCompareElement extends Components.LocalCompare, HTMLStencilElement {}
  var HTMLLocalCompareElement: {
    prototype: HTMLLocalCompareElement;
    new (): HTMLLocalCompareElement;
  };

  interface HTMLLocalPixelmatchElement extends Components.LocalPixelmatch, HTMLStencilElement {}
  var HTMLLocalPixelmatchElement: {
    prototype: HTMLLocalPixelmatchElement;
    new (): HTMLLocalPixelmatchElement;
  };

  interface HTMLScreenshotLookupElement extends Components.ScreenshotLookup, HTMLStencilElement {}
  var HTMLScreenshotLookupElement: {
    prototype: HTMLScreenshotLookupElement;
    new (): HTMLScreenshotLookupElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'local-compare': HTMLLocalCompareElement
    'local-pixelmatch': HTMLLocalPixelmatchElement
    'screenshot-lookup': HTMLScreenshotLookupElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'local-compare': HTMLLocalCompareElement;
    'local-pixelmatch': HTMLLocalPixelmatchElement;
    'screenshot-lookup': HTMLScreenshotLookupElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
