/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core'
import 'ionicons'


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ScreenshotCompare {}
  interface ScreenshotCompareAttributes extends StencilHTMLAttributes {}

  interface ScreenshotDetail {}
  interface ScreenshotDetailAttributes extends StencilHTMLAttributes {}

  interface ScreenshotList {}
  interface ScreenshotListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'ScreenshotCompare': Components.ScreenshotCompare;
    'ScreenshotDetail': Components.ScreenshotDetail;
    'ScreenshotList': Components.ScreenshotList;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'screenshot-compare': Components.ScreenshotCompareAttributes;
    'screenshot-detail': Components.ScreenshotDetailAttributes;
    'screenshot-list': Components.ScreenshotListAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLScreenshotCompareElement extends Components.ScreenshotCompare, HTMLStencilElement {}
  var HTMLScreenshotCompareElement: {
    prototype: HTMLScreenshotCompareElement;
    new (): HTMLScreenshotCompareElement;
  };

  interface HTMLScreenshotDetailElement extends Components.ScreenshotDetail, HTMLStencilElement {}
  var HTMLScreenshotDetailElement: {
    prototype: HTMLScreenshotDetailElement;
    new (): HTMLScreenshotDetailElement;
  };

  interface HTMLScreenshotListElement extends Components.ScreenshotList, HTMLStencilElement {}
  var HTMLScreenshotListElement: {
    prototype: HTMLScreenshotListElement;
    new (): HTMLScreenshotListElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'screenshot-compare': HTMLScreenshotCompareElement
    'screenshot-detail': HTMLScreenshotDetailElement
    'screenshot-list': HTMLScreenshotListElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'screenshot-compare': HTMLScreenshotCompareElement;
    'screenshot-detail': HTMLScreenshotDetailElement;
    'screenshot-list': HTMLScreenshotListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
